"""followers

Revision ID: 789bb9a6d8ac
Revises: d88b1b9d3850
Create Date: 2020-12-13 20:12:29.425736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789bb9a6d8ac'
down_revision = 'd88b1b9d3850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
